apiVersion: pgupgrade.zzh.domain/v1
kind: PgUpgrade
metadata:
  labels:
    app.kubernetes.io/name: pgupgrade
    app.kubernetes.io/instance: pgupgrade-sample
    app.kubernetes.io/part-of: k8s-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: k8s-operator
  name: pgupgrade-sample
spec:
  # TODO(user): Add fields here
  # image: postgres
  # subname: zzhsub1
  # dbname: mydatabase
  # pubname: pub
  # # olddbhost: '10.244.0.76'
  # olddbhost: "10.244.0.168"
  # olddbport: "5432"
  # olddblabel: postgres-master
  # pgdumpfilename: test_dump.sql

  # pgdump: true

  # finishsync: false
  # killdeployments:
  #   - pg-delete-test

  ### delete test ####
  image: postgres
  subname: zzhsub_delete
  dbname: mydatabase
  pubname: my_pub_delete
  # olddbhost: '10.244.0.76'
  olddbhost: "10.244.1.43"
  olddbport: "5432"
  olddblabel: postgres-master
  pgdumpfilename: table_1.sql

  pgdump: true

  finishsync: true
  killdeployments:
    - postgres-delete-test

status:
  upgrade: false
